### ISSUE TITLE
pack management behind a proxy

### ISSUE THREAD

**Issue by fred-r** [Open-CMSIS-Pack/cpackget#38]
In my company we are working behind a proxy.

I am under the impression that when I use pack management tools (cpackget or uvision) then some internet accesses are made and alter my pidx file because of the proxy:
C:\CMSIS_PACKS.Web\index.pidx:
```
```
<!DOCTYPE html><html><head><title>Welcome To Zscaler Directory Authentication</title>
...
```

Is it possbile to:
- either handle the proxy
- or have a mode with only local files ?

**Comment by jeromecoutant** [comment]
Are http_proxy and https_proxy environment variables used for cpackget ?

**Comment by chaws** [comment]
Cpackget is written in Golang, which [supposedly](https://pkg.go.dev/net/http#ProxyFromEnvironment) tweaks its transport layer depending on the HTTP_PROXY/http_proxy env vars, but I have tried it without success though.

I'll tackle that, and will make cpackget either read HTTP(S)_PROXY environment variable or accept it as a cmdline arg, e.g. `--proxy https://[user:pass@]proxy.com[:port]`

**Comment by jeromecoutant** [comment]
Maybe it is an issue with redirection ?

`curl -O http://www.keil.com/pack/index.pidx` => wrong file
`curl -L -O http://www.keil.com/pack/index.pidx` => OK

So cpackget is first using http_proxy env vars, but after redirection no?

**Comment by chaws** [comment]
@jeromecoutant, @fred-r  I re-checked and `HTTP_PROXY` and `HTTPS_PROXY` work fine as-is.

`cpackget` will use `HTTP_PROXY` (if any) for http requests and `HTTPS_PROXY` (if any) for https requests.
I failed to check that in my previous comment because I had used a non-https proxy configuration with a https url so the proxy was never used. It was my mistake, sorry about that!

I also noticed I implemented a hard check on using non-https url for `http://www.keil.com/pack/index.pidx`. I have patched it now to display a warning instead of raising an error:
```bash
$ export HTTP_PROXY=http://127.0.0.1:8080 # or set HTTP_PROXY=127.0.0.1:8080 on Windows
$ export CMSIS_PACK_ROOT=/tmp/temp-pack-root
$ ./build/cpackget init http://www.keil.com/pack/index.pidx
I: Using pack root: "/tmp/temp-pack-root"
W: "/tmp/temp-pack-root/.Web/index.pidx" not found. Creating a new one.
I: Overwriting public index file /tmp/temp-pack-root/.Web/index.pidx
W: Non-HTTPS url: "http://www.keil.com/pack/index.pidx"
I: Downloading index.pidx 100% |█████████████████████████████████████| (99/99 kB, 121.386 kB/s)
```

I was working on a patch to allow passing this configuration via cmdline args, but since this works just the way it is, I'll just add a note on the README.md on how to use proxy.

Does that sound OK with you guys?

**Comment by chaws** [comment]
@jeromecoutant I have added a note on configure proxy with cpackget: https://github.com/Open-CMSIS-Pack/cpackget/pull/45/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R128

**Comment by chaws** [comment]
Hi @fred-r, @jeromecoutant I have added a note explaining how to do the setup when working behind a proxy: https://github.com/Open-CMSIS-Pack/cpackget#working-behind-a-proxy

Could you please confirm that works for your use case?
