### ISSUE TITLE
Cpackget is installing a wrong pack version

### ISSUE THREAD

**Issue by chaws** [Open-CMSIS-Pack/cpackget#48]
**Describe the bug**
Cpackget should raise an error when specifying a minimum version that does not exist

**To Reproduce**
```bash
$ cpackget pack add "ARM::CMSIS>=10.0.0"
I: Using pack root: "../packroot"
I: Adding pack "ARM::CMSIS>=10.0.0"
I: Extracting files to ../packroot/ARM/CMSIS/5.8.0 100% |████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| (8133/8133, 7742 it/s)
```

**Expected behavior**
I think in this case, the expected behavior should be an error message saying that the desired version is not available in any PDSC file

**Comment by jkrech** [comment]
I do agree. There is no published version of the pack available that satisfies the version requirement.
The statement "not available in any PDSC" is confusing to me. What do you refer to with "any PDSC file"?
If the specified pack is a public pack then there is only one pdsc you can look at for finding the requested version, right?
./Web/<vendor>.<packname>.pdsc
If it is not in there, the only alternative is to look in ./Local and see whether there is a <url> and a <release> tag you could use to locate the pack version satisfying the command line.
Files in local_repository.pidx are individual local versions that should not be considered as part of finding a new version. However you should consider the referenced version whether it satisfies the version requirement from the command line already (so you don't need to install any new pack).
What am I missing?

**Comment by chaws** [comment]
> What do you refer to with "any PDSC file"?

By "_any_", I mean both PDSC files of a public (.Web) and a local (.Local) packs. Because both of these scenarios might be checked (if not available in .Web, look under .Local) when installing a pack. Perhaps a more meaningful message fits better here "Pack version not found in path-to-pdsc-file.pdsc". 

Sorry I don't understand how packs listed in `local_repository.pidx` can be useful here. I say this because no pack will actually get installed that way. No?

**Comment by jkrech** [comment]
Let's assume someone has ARM.CMSIS.5.9.0 in a folder somewhere and registered it's pdsc file to the local_repository.
If you run cpackget pack add ARM.CMSIS@>5.7.0 then the request is already satisfied, isn't it?

**Comment by lud0v1c** [comment]
> Let's assume someone has ARM.CMSIS.5.9.0 in a folder somewhere and registered it's pdsc file to the local_repository. If you run cpackget pack add ARM.CMSIS@>5.7.0 then the request is already satisfied, isn't it?

This sounds correct to me. The correct behavior should be to install the lowest possible ARM.CMSIS pack correct? And if only 5.9.0 is available, no error but an info message should be printed saying it's already installed right? If no version above 5.7.0 was found, then it should return an error.
Just trying to understand the problem here

**Comment by lud0v1c** [comment]
That makes more sense to me, thanks @chaws.

**Comment by jkrech** [comment]
I agree with 1 and 2.
Regarding 1) I just want to ensure that we are all aligned how the list of installed pack versions is created.
a) find all installed pack versions
b) read all pdsc files listed in local_repository.pidx to identify their pack version. If a pack version already exists in a) overwrite it's location

This combined list of pack versions should be used for
a) list installed packs
b) check whether a version range condition is already satisfied by installed packs or not

**Comment by lud0v1c** [comment]
@jkrech Regarding issue 1: does the order matter in a) and b)? As it currently stands, the list generated in a) contains all packs/versions, I was thinking of creating that empty list first (installedVersions), checking the local_repository for all the installed versions and appending them to the list, and then the rest of the process follows as usual (checking what is locally installed or not, the local ones would also be considered since it's the same list).

One sanity check I was going to write, that also illustrates my interpretation of issue 1:
1) Install .psdc TheVendor.DevPack.1.2.4.pdsc
2) Try to install public pack TheVendor.DevPack.1.2.4 (same exact pack but present in the public index)
3) An error/message should be presented as the pack was already installed in step 1

**Comment by jkrech** [comment]
@lud0v1c  we can either install a pack or add a reference of the pdsc to the local_repository.pidx!
Therefore I can install the same pack version that is already referenced by as pdsc in the local_repository.pidx
Effectively the tools will not look at the installed pack version because the one listed in local_repository.pidx will take precedence.
However, if the user lowers the version in the referenced pdsc the installed pack version will get considered.
I don't know how you search for pack versions in that list, however if you want to ensure that the pack version from the local_repository.pidx always take precedence and you search through the list from top to botton, then the local_repository.pidx pack versions need to come first.
